### ISSUE TITLE
Needs Updating?

### ISSUE THREAD

**Issue by jermsam** [scotch-io/react-router-course#2]
Trying to follow your tutorials but getting:
error react-router-demo@1.0.0: The engine "node" is incompatible with this module. Expected version "6.10.3".
error Found incompatible module
my node -v is 9.5.0

**Comment by jermsam** [comment]
had to change this in package.json.
From:
"engines": {
    "node": "6.10.3"
  },
To:
"engines": {
    "node": "9.5.0"
  },

**Comment by chris-sev** [comment]
Thanks for letting us know. Added a `"node": ">=6.10.3"` so anything above 6 works also.
